# package setup
library(usethis)
create_package("/workspace/workspace_pipelines/blaseRdata")
use_mit_license("Brad Blaser")
use_package("blaseRtools", type = "imports")
use_package("tidyverse", type = "imports")
use_package("monocle3", type = "imports")
use_package("cowplot", type = "imports")
use_package("readxl", type = "imports")
use_package("fastSave", type = "imports")
use_readme_md()
use_news_md()
use_git()
use_github(private = TRUE)
use_data_raw()
